'use strict';

const DashboardActions = [
    'error',
    'loading',
    'loadUser',
    'loadedUser',
    'loadData',
    'loadedData',
    'loadDashboards',
    'loadedDashboards',
    'loadDashboard',
    'loadedDashboard',
    'createDashboard',
    'editDashboard',
    'editedDashboard',
    'deleteDashboard',
    'deleteDashboards',
    'deletedDashboards',
    'loadUsers',
    'loadedUsers',
    'loadSharing',
    'loadedSharing',
    'shareWithUsers',
    'sharedWithUsers',
    'removeShare',
    'removedShare',
    'toggleMediaMenu',
    'toggleEmbedMenu',
    'toggleLibraryMenu',
    'toggleVisualizationMenu',
    'confirmDelete',
    'toggleSharingModal',
    'toggleCustomize',
    'createCard',
    'createdCard',
    'editCard',
    'editedCard',
    'editCards',
    'toggleMenu',
    'deleteCard',
    'deletedCard',
    'loadVisualizationData',
    'loadedVisualizationData'
];

export default DashboardActions;